name: ActionCustomRom

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps

    - name: Prepare the environment
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get -y upgrade
        sudo apt-get -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libncurses5 libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      
    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "U89-sk"
        git config --global user.email "browsmail.git@gmail.com"
        repo init -u https://github.com/bananadroid/android_manifest.git -b 13
      id: pwd
          
    - name: Repo Sync
      run: |
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune
        repo sync --force-sync
      working-directory: workspace
      
    - name: Clone device tree
      run: |
        git clone https://github.com/Think-Thought/device_realme_RMX1851 -b bananadroid ./device/realme/RMX1851
        git clone https://github.com/Think-Thought/android_vendor_RMX1851 ./vendor/realme/RMX1851
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building rom
      run: |
        source build/envsetup.sh
        export USE_CCACHE=1 && export CCACHE_EXEC=/usr/bin/ccache && ccache -M 50G
        export LC_ALL=C
        export CONFIG_STATE_NOTIFIER=y
        export SELINUX_IGNORE_NEVERALLOWS=true
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch banana_RMX1851-userdebug && make clean && m banana -j$(nproc --all)
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      run: |       
        curl -sL https://git.io/file-transfer | sh
         ./transfer wet out/target/product/RMX1851/BananaDroid*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
